### ISSUE TITLE
swisscollnet: images

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#101]
Using `id.gbif.ch/989939123` as an example

**Missing image URL**
Entity `id.gbif.ch/3392823314` has `"accessUri": "id.gbif.ch/MHNG-MAM-1079.094/img/820337831",`

Please change your access URI to a url for your image

**Comment by MortenHofft** [comment]
Same goes for accessUri on sequences I see. E.g. `id.gbif.ch/MHNG-MAM-1804.094/seq/75011`

**Comment by timrobertson100** [comment]
Fixed by @SofiaWyler and @tschudip 

http://labs.gbif.org:7003/?entityId=id.gbif.ch%2F989939123
