### ISSUE TITLE
arctos: digital entities doesn't appear in relationship table

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#109]
@dustymc
Digital entities are floating without relations to other items
For example entity/digitalEntity `https://arctos.database.museum/media/10438899`

It should be linked to something I assume. I would expect an entry in the relationships table

**Comment by dustymc** [comment]
Correct, because this is a partial export and I didn't bother filtering some things. That particular example will be handled when https://arctos.database.museum/collection/UAMb:Herb is included, but there will probably always be floaters unless I need to explicitly exclude them.

**Comment by MortenHofft** [comment]
No need
