### ISSUE TITLE
arctos: organism scope = catalog record

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#112]
https://dwc.tdwg.org/terms/#dwc:organismScope

@dustymc As I read the dwc specs this isn't the intended usage for `organismScope`

**Comment by dustymc** [comment]
@tucotuco any suggestions? ("Whatever someone felt like cataloging, how would I know?!" is strangely absent from the suggested vocabulary!)

**Comment by timrobertson100** [comment]
Hehe

Sounds like `unknown` is the best that could go here, or just leave it as `null`

**Comment by dustymc** [comment]
>null

!!! Thanks, in next export.
