### ISSUE TITLE
Arctos: references not used

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#113]
@dustymc the reference table is free floating without anything linking it to entities. I would expect a citation table that made that connection.

example of a not used reference:
```
https://arctos.database.museum/publication/144,journal article,"C. S. Davis, T. S. Gelatt, D. Siniff, C. Strobeck. 2002. Dinucleotide microsatellite markers from the Antarctic seals and their use in other Pinnipeds. Molecular Ecology Resources 2:203-208.",2002,,t
```

**Comment by dustymc** [comment]
woops, table citation in next export, thanks

**Comment by tucotuco** [comment]
Citations have been included in the latest export. Closing.
