### ISSUE TITLE
Arctos: media part of organism

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#114]
@dustymc

first entry in relationship table
```
entity_relationship_id,depends_on_entity_relationship_id,subject_entity_id,entity_relationship_type,object_entity_id,object_entity_iri,entity_relationship_date,entity_relationship_order
599250445,,https://arctos.database.museum/guid/MSB:Host:1,part of,https://arctos.database.museum/guid/MSB:Host:1/PID21849259,,,1
```

So 
**subject**: https://arctos.database.museum/guid/MSB:Host:1
**type**: part of
**object**: https://arctos.database.museum/guid/MSB:Host:1/PID21849259

I read that as https://arctos.database.museum/guid/MSB:Host:1 is a `part of` https://arctos.database.museum/guid/MSB:Host:1/PID21849259

But https://arctos.database.museum/guid/MSB:Host:1/PID21849259 is a media item.

This looks odd to me. At least I would have expected something like `skull : part of : organism` and not `organism: part of: media`. Is this a mistake or is the intention something else?

**Comment by dustymc** [comment]
thank you, swapped for next export
