### ISSUE TITLE
Arctos: rename relationship type

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#115]
@dustymc
relation type `shows cataloged_item` is reversed I believe. And it would help me if we could rename it to `IMAGE OF`.

example record
```
599301211,,https://arctos.database.museum/guid/MSB:Host:2932,shows cataloged_item,https://arctos.database.museum/media/10431068,,,1
```

**Swap subject and object**
subject: https://arctos.database.museum/guid/MSB:Host:2932 is a MATERIAL_ENTITY
object: https://arctos.database.museum/media/10431068 is a DIGITAL_ENTITY

Material entity : shows cataloged_item : Digital entity

subject and object should be swapped as far as I can see.

**Rename**
And if you could rename it to `IMAGE OF` then it would be the same as the other groups. That isn't to say that `shows cataloged_item` isn't more precise - it is just useful at this point to keep it the same if possible. It makes building a UI a lot easier.

**Comment by dustymc** [comment]
>reversed

Thank you, reversed for next release.

>rename it to IMAGE OF

I can, but please confirm that "anything at a URI" is OK as "IMAGE OF"

(And for completeness, here's what we'd like to eventually share: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_relationship)

Or perhaps this stems back to my mapping of digital_entity.digital_entity_type - I don't have some 'required' information so I've made some sorta-wild guesses from https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmime_type (and perhaps https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_type would be a better source?).

```

       -- ugh, how the heck am I supposed to know?
      case
        when media.mime_type in ('image/dng','image/jpeg','image/png','image/tiff','model/stl') then 'STILL_IMAGE'
        when media.mime_type in ('audio/mpeg3','video/mp4','audio/x-wav') then 'SOUND'
        when media.mime_type in ('video/quicktime') then 'MOVING_IMAGE'
        else 'TEXT'
    end,
```

**Comment by MortenHofft** [comment]
> (And for completeness, here's what we'd like to eventually share: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_relationship)

That makes sense. I do not believe that is possible now. For example linking images to the event `shows collecting_event`. 
I'll leave it to others (@tucotuco) to decide if that is something the model should accommodate or not.

**Comment by MortenHofft** [comment]
https://github.com/gbif/model-material/blob/master/data-mapping.md#7-digitalentities
```
CREATE TYPE DIGITAL_ENTITY_TYPE AS ENUM (
  'DATASET',
  'INTERACTIVE_RESOURCE',
  'MOVING_IMAGE',
  'SERVICE',
  'SOFTWARE',
  'SOUND',
  'STILL_IMAGE',
  'TEXT',
  'GENETIC_SEQUENCE'
);
```

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_type looks like a decent match. But I'm not sure what you would do with e.g. `3D model` if that is a file. 
But you could perhaps share those as links?
E.g. `subject: CatalogedItem | relation: has 3d model | object_entity_iri: http://my_interactive_3d.model_website`

**Comment by MortenHofft** [comment]
> I can, but please confirm that "anything at a URI" is OK as "IMAGE OF"

I'm not sure I understand. But I imagined that you would swap subject/object. And rename `shows cataloged_item` to `IMAGE_OF` and then the DIGITAL_ENTITY that is the subject of that new relation would have an access URI that points to a jpg.

**Comment by dustymc** [comment]
>swap subject/object.

yes

>subject: CatalogedItem | relation: has 3d model |

Oh I see, maybe - but I don't see why it's here, in the relationship, rather than just as an attribute of the object (because 'this is an image' is clearly an attribute of the object and does not in any way that I can see affect what relationships involving the object can be made??).

Anyway, I did this - it can be adjusted as necessary:

```
case
        when media.media_type='image' then 'IMAGE_OF'
        else concat('has ',media.media_type)
    end,
```
??????

**Comment by MortenHofft** [comment]
Just to make it clear: I'm not the model expert. I'm just trying to consume the data. Ideally feedback from you as a publisher and me as a consumer will inform the model work.

--------

Wonderful - except could you make that `IMAGE OF` and not `IMAGE_OF`.

> I don't see why it's here, in the relationship, rather than just as an attribute of the object

I tend to think you are right. I believe that `IMAGE OF` (or whatever the relation should be called. e.g. `SHOWS ITEM`) would work just as fine if the digital entity type could tell me what it is. And in fact BGBM use that relation type to link to both `STILL_IMAGE` and `INTERACTIVE_RESOURCE`

My example with the 3d model is simply that I'm not sure what digital entity type it would map to. So if you want to share a `.stl | .obj` extensions, then I wouldn't know what [digital entity type](https://github.com/gbif/model-material/issues/115#issuecomment-1477881225) to choose. In those cases adding it as an external object looks like the best option? unless one of the existing types is already intended to capture 3d models

**Comment by dustymc** [comment]
Thanks for the clarification, familiar perspective!

Changed.

>use that relation type to link to both

In case it's useful at some point: I don't know what Arctos links to. Media is "something with a URI" (and some of those are local systems, password-protected, etc. - I _can't_ know what's out there). That's probably a link to MorphoSource, but there are some CT scans stored locally and presumably they're linked in somewhere. (They'd be parents of the "viewable" media which is attached to records if I'd have set them up - and I don't think that's yet shared.)

**Comment by MortenHofft** [comment]
From the latest export
relationship file
`601082873,,https://arctos.database.museum/guid/MSB:Para:19030,IMAGE OF,https://arctos.database.museum/media/10426137,,,1`

subject: parasite
relation: IMAGE OF
object: media

That should be `subject:media is IMAGE OF object:parasite` right?

**Comment by tucotuco** [comment]
It was a very talented parasite.

**Comment by tucotuco** [comment]
This has been corrected in the latest export. Closing.
