### ISSUE TITLE
Arctos: "part of" vs "MATERIAL SAMPLE OF"

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#119]
@dustymc?
I have seen the relationship type `MATERIAL SAMPLE OF` used in other data exports

I assume that `A is part of B` has the same meaning as `A is MATERIAL SAMPLE OF of B`.
Would it be possible for you to rename that in the export? To use `MATERIAL SAMPLE OF` instead of `part of`?

**Comment by dustymc** [comment]
wilco
