### ISSUE TITLE
Arctos: missing relations

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#121]
@dustymc
Taking https://arctos.database.museum/guid/MSB:Host:20914 as an example record

The arctos website mentions a parasite in the relationships.
That isn't present in the exported data.

Since the parasite isn't in the export I suppose the best way is to do
```
Subject: https://arctos.database.museum/guid/MSB:Host:20914
Relation: has parasite
object_entity_iri: https://arctos.database.museum/guid/MSB:Para:18693 <== and if/when this entity gets published, then point to that instead
```

**Comment by tucotuco** [comment]
This is an issue that will resolve itself naturally with a complete Arctos export. The idea was to use a single collection to test the mappings. Maybe it is time to include a second, collection in the export, the MSB:Para collection, to test these relationships too. @dustymc Can you add that one? Or is it a pain? If it is a pain, it might almost be time to do the entire export.
