### ISSUE TITLE
Location: should locationID be repeated for child events?

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#122]
@tucotuco 
If the parent event has a location - should the child events then also repeat the locationID or is that inherited?

I notice that Specify and Arctos do it differently.

I suspect your answer is: both are allowed and it is inherited. 
So far I have just assumed it was explicit.

**Comment by tucotuco** [comment]
The Location of a parent Event is expected to completely encompass the Locations of all of its children. There is no inheritance. They must all be explicit. Surprise!

**Comment by MortenHofft** [comment]
@dustymc
I take that to mean that row one below should repeat the locationID of the parent event

|event_id                                                                           |parent_event_id                                                                    |dataset_id|location_id                                                                |protocol_id|event_type    |event_name|field_number|event_date|year|month|day|verbatim_event_date|verbatim_locality|verbatim_elevation|verbatim_depth|verbatim_coordinates|verbatim_latitude|verbatim_longitude|verbatim_coordinate_system|verbatim_srs|habitat|protocol_description   |sample_size_value|sample_size_unit|event_effort|field_notes|event_remarks|
|-----------------------------------------------------------------------------------|-----------------------------------------------------------------------------------|----------|---------------------------------------------------------------------------|-----------|--------------|----------|------------|----------|----|-----|---|-------------------|-----------------|------------------|--------------|--------------------|-----------------|------------------|--------------------------|------------|-------|-----------------------|-----------------|----------------|------------|-----------|-------------|
|https://arctos.database.museum/guid/MSB:Host:24585?seid=5159436                    |https://arctos.database.museum/place.cfm?action=detail&collecting_event_id=11930219|Arctos    |                                                                           |           |collection    |          |            |          |    |     |   |                   |                 |                  |              |                    |                 |                  |                          |            |       |collecting_source: wild|                 |                |            |           |             |
|https://arctos.database.museum/place.cfm?action=detail&collecting_event_id=11930219|                                                                                   |Arctos    |https://arctos.database.museum/place.cfm?action=detail&locality_id=11454854|           |eventing event|          |            |2019-09-30|    |     |   |2019-09-30         |Prospect Pond    |                  |              |36.92145/-121.826441|                 |                  |                          |            |       |                       |                 |                |            |           |             |
