### ISSUE TITLE
Arctos: swap relationships

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#123]
@dustymc 
I still think the relations look wrong

https://arctos.database.museum/guid/MSB:Para:18693
is type: organism

https://arctos.database.museum/guid/MSB:Para:18693/PID22810670
is type: part

The relationship says:
subject:organism is `MATERIAL SAMPLE OF` object:part

|entity_relationship_id|depends_on_entity_relationship_id|subject_entity_id                                 |entity_relationship_type|object_entity_id                                              |object_entity_iri|entity_relationship_date|entity_relationship_order|
|----------------------|---------------------------------|--------------------------------------------------|------------------------|--------------------------------------------------------------|-----------------|------------------------|-------------------------|
|601051164             |                                 |https://arctos.database.museum/guid/MSB:Para:18693|MATERIAL SAMPLE OF      |https://arctos.database.museum/guid/MSB:Para:18693/PID22810670|                 |                        |1                        |

**Comment by tucotuco** [comment]
The subjects and objects for these relationships have been corrected in the latest export. All good @MortenHofft ?
