### ISSUE TITLE
Arctos: locationIDs should be filled for all events

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#124]
@dustymc
See Location: should locationID be repeated for child events](https://github.com/gbif/model-material/issues/122#top)

I take that to mean that row one below should repeat the locationID of the parent event

|event_id                                                                           |parent_event_id                                                                    |dataset_id|location_id                                                                |protocol_id|event_type    |event_name|field_number|event_date|year|month|day|verbatim_event_date|verbatim_locality|verbatim_elevation|verbatim_depth|verbatim_coordinates|verbatim_latitude|verbatim_longitude|verbatim_coordinate_system|verbatim_srs|habitat|protocol_description   |sample_size_value|sample_size_unit|event_effort|field_notes|event_remarks|
|-----------------------------------------------------------------------------------|-----------------------------------------------------------------------------------|----------|---------------------------------------------------------------------------|-----------|--------------|----------|------------|----------|----|-----|---|-------------------|-----------------|------------------|--------------|--------------------|-----------------|------------------|--------------------------|------------|-------|-----------------------|-----------------|----------------|------------|-----------|-------------|
|https://arctos.database.museum/guid/MSB:Host:24585?seid=5159436                    |https://arctos.database.museum/place.cfm?action=detail&collecting_event_id=11930219|Arctos    |                                                                           |           |collection    |          |            |          |    |     |   |                   |                 |                  |              |                    |                 |                  |                          |            |       |collecting_source: wild|                 |                |            |           |             |
|https://arctos.database.museum/place.cfm?action=detail&collecting_event_id=11930219|                                                                                   |Arctos    |https://arctos.database.museum/place.cfm?action=detail&locality_id=11454854|           |eventing event|          |            |2019-09-30|    |     |   |2019-09-30         |Prospect Pond    |                  |              |36.92145/-121.826441|                 |                  |                          |            |       |                       |                 |                |            |           |             |

**Comment by dustymc** [comment]
I had that as:

>    null, --location_id: doesn't seem appropriate here, this is going to an event which has that

I think my idea was to force traffic through the "eventing events" (that's another plea for help, by the way!) where a user might notice that a host and a whole bunch of parasites (or whatever) were hanging out together, find habitat photos, etc., but I think maybe it doesn't matter? Added for next export.

**Comment by MortenHofft** [comment]
I wondered what that meant and looked it up the other dat. Apparently a special sort of horse riding competition

**Comment by dustymc** [comment]
I probably should have stuck with tatertots!

**Comment by tucotuco** [comment]
> I had that as:
> 
> > null, --location_id: doesn't seem appropriate here, this is going to an event which has that
> 
> I think my idea was to force traffic through the "eventing events" (that's another plea for help, by the way!) where a user might notice that a host and a whole bunch of parasites (or whatever) were hanging out together, find habitat photos, etc., but I think maybe it doesn't matter? Added for next export.

I hear the plea. 

I have been looking at the page that come up resolving the event identifiers to try to understand what those two types of Events are. It looks like an seid= Event corresponds with an Occurrence, but I can't tell what a collecting_event_id= Event is.

**Comment by dustymc** [comment]
"Eventing events" are just events, but (unlike GUM) we don't _do_ anything there - they're place (from locality) plus time (and some weird verbatim stuff that's perhaps best ignored for now). 

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_event_type - ing-events (probably all 'collecting' in these data) are in Arctos the connection between records and events, contain habitat and method (each of the 67 kinds of parasites can be collected in different places using different techniques), and are in fact what we hinge Occurrence approximations off of.

"Occurrence" including Event Type: and Collecting Source: and such: https://arctos.database.museum/guid/MSB:Para:28915?seid=4276075

event: https://arctos.database.museum/place.cfm?action=detail&collecting_event_id=11313436

locality: https://arctos.database.museum/place.cfm?action=detail&locality_id=10997087

(and geography, which was feeling left out: https://arctos.database.museum/place.cfm?action=detail&geog_auth_rec_id=1004484)

**Comment by dustymc** [comment]
Other way 'round. The formerly-eventing - future-just-event events are - well, events. Place-at-time at which many (or none, some exist to hold Media and etc.) things could be "ctspecimen_event_type-ed." Arctos table is https://arctos.database.museum/tblbrowse.cfm?tbl=collecting_event

"ctspecimen_event_type-ing" events (probably all 'collecting' here) are where/when specific things happen to specific records. Table https://arctos.database.museum/tblbrowse.cfm?tbl=specimen_event in Arctos, plus some replication from above.

The parents will precisely spatiotemporally cover their children (because only the former exist in Arctos, the latter are just the record-specific stuff, with replicated when/where for GUM).

**Comment by tucotuco** [comment]
Seems like we have no problems then, aside from what started the conversation, which was to provide location_id for all Events. Does that seem right @dustymc @MortenHofft ?

**Comment by tucotuco** [comment]
All Events have location_ids in the latest export. All good @MortenHofft?
