### ISSUE TITLE
Enrich BGBM data

### ISSUE THREAD

**Issue by timrobertson100** [gbif/model-material#127]
[This paper](https://doi.org/10.5091/plecevo.97453) has [morphological characters](https://plecevo.eu/article/97453/download/suppl/31/) about two of the specimens published in the 
BGBM collection which are not part of the published data.

We should demonstrate through an additional script, that data can be loaded into the GUM view to enrich the data shared from the source.

**Comment by tucotuco** [comment]
Does this exercise include pretending to "publish" those data from the paper as a dataset?

**Comment by timrobertson100** [comment]
Probably cutting corners but yes.

I anticipate this bringing in 1) assertions against the material and a 2) a journal and material citations connecting them.

Anticipating why you asked: This will need me to add dataset_id to assertions, and possibly other places. To avoid modifying the schema for others, I was going to run a final enrichment script that modified tables and populated them. I don't anticipate anything I'd do as being a final design (none of this is anyway).

Seem OK?

**Comment by tucotuco** [comment]
I have no problem with it at all if it achieves your goal. Was just wondering about the scope of that goal.

**Comment by timrobertson100** [comment]
The traits for [B 10 0166362](http://labs.gbif.org:7003/?entityId=B%2010%200166362) and [B 10 0166305](http://labs.gbif.org:7003/?entityId=B%2010%200166305) are now added.

@tucotuco - of interest here, are 3 agents that are associated with the traits. I chose not to create agents (for now) but the data model in this exercise would not allow it due to the single agent ID.

I am yet to create the material citations

**Comment by tucotuco** [comment]
@timrobertson100 The model does allow multiple agents to be grouped and given an id that can be linked in any agent_id foreign key. It would be a new Agent with AgentRelationships to join the group to the members.

**Comment by timrobertson100** [comment]
Ah yes. I overlooked the group again. 

When we review everything I wonder if it will be more intuitive to have arrays `TEXT[] agent_id` in certain places to simplify things.

**Comment by tucotuco** [comment]
In implementation that seems reasonable. What concerns me more are the publishing models. We're finding the underlying model to be a lot for people to handle, even when they begin with relational models.
