### ISSUE TITLE
Taxon: missing nameAccordingToID

### ISSUE THREAD

**Issue by timrobertson100** [gbif/model-material#14]
I think we missed `nameAccordingToID` in the schema. 
Do you agree that was just my oversight @tucotuco, please, as Markus and I simplified the Taxon removing the confusing terms?

**Comment by tucotuco** [comment]
I would have thought so, yes. The model diagram is utterly sparse. The schema renditions reflect the experience at GBIF if I understand correctly.

**Comment by timrobertson100** [comment]
Thanks for confirming. I will add this
