### ISSUE TITLE
Taxa model - Major Linnean ranks

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#17]
I see we use kingdom, phylum, ... in the model for taxa

Should the model accommodate a future where major Linnean ranks isn't the only option? I do not know enough about how that would work, but something like:

```
classification: [
  ...
  {
   rank: GIGA_CLASS
   name: something
  },
  {
   rank: UNKNOWN_CLADE
  },
  ...
]
```

In the current version it might just be a result of it being a DwCA that is the source.

**Comment by timrobertson100** [comment]
Does this help answer this question perhaps?
https://github.com/gbif/model-material/blob/master/schema.sql#L471 

We anticipate we will get people providing one or the other in this excercise
