### ISSUE TITLE
associatedSequences automatically filled?

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#21]
When comparing to 
https://raw.githubusercontent.com/gbif/model-material/master/java-sdk/koldingensis/data.json
and
https://github.com/gbif/model-material/blob/koldingensis/java-sdk/koldingensis/Occurrence.tsv

I notice that the preserved specimen has `associatedSequences` filled in the DB, but not at source

It looks like the data from the material sample has been moved to the preserved specimen. Is that on purpose?

**Comment by timrobertson100** [comment]
>  Is that on purpose?

No. 

Bear in mind we're not using that source as definitive now. We will drift from that with other information we can find.
