### ISSUE TITLE
Missing vernacularName in Taxon

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#23]
`vernacularName` ought to be in the taxon according to [spreadsheet](https://docs.google.com/spreadsheets/d/1f_oK9ImZqgSA5sYFQmx7n2uoRI9FmOs-vVCP1KspHeA/edit#gid=0 ), but isn't included in the DB schema

I notice the comment 
>This will only really work with something like a language-capable thesaurus with entityID, entityName, entityNameLanguageCode, entityNameIsAccepted, entityNameRemarks

which might be why it is left out

**Comment by timrobertson100** [comment]
Yes - it was omitted by choice as it seemed too simple a model to make sense.

We could add it if really needed in this exercise, but if we're really trying to link data across datasets the taxon entry will be reused and I fear we'll quickly need a more expressive model than this single field. I suggest we leave it out unless we end up really needing it now.

**Comment by MortenHofft** [comment]
At this point I'm just trying to figure out where data from the DwcA goes. I'm happy to leave it out though as I agree it is hard to use in the current form.
