### ISSUE TITLE
`identification` table confusion

### ISSUE THREAD

**Issue by raffael-mnhn** [gbif/model-material#28]
The table `identification` links an identifier actor using the `identified_by` field, what does `identified_by_id` do?

```
CREATE TABLE identification (
  identification_id TEXT PRIMARY KEY,
  organism_id TEXT, -- foreign key declared after organism table
  identification_type TEXT NOT NULL,
  taxon_formula TEXT NOT NULL,
  verbatim_identification TEXT,
  type_status TEXT,
  identified_by TEXT, <--------------
  identified_by_id TEXT, <----------------
```

**Comment by timrobertson100** [comment]
Thanks, @raffael-mnhn - I can see this may be confusing.

This was an attempt to be able to accommodate two scenarios:

1. Where someone really is providing a table of Agents and attaching them using the roles (i.e. an entry in `Agent` and the `AgentRole`)
2. Simpler data, where only the name and identifier (e.g. an ORCID or Harvard Herbarium ID) for the person making the identification is known. In that scenario, you would populate those fields only, and not create entries.

Does that help please?

**Comment by raffael-mnhn** [comment]
I must admit I only now understand the thing about either using explicit or implicit links to Agents. If I understand correctly you would either:

1. Use `agent_role` to connect an `agent` to any entity. In this case, none of the fields `identified_by` or `identified_by_id` would be used.
2. Use `identified_by` to store the name (e.g. John Doe) and / or `identified_by_id` to store a unique external id like an ORCID.

**Comment by tucotuco** [comment]
I agree with what Tim says, a general principle would be to fill in every field that can be filled in, even if it seems redundant.

**Comment by timrobertson100** [comment]
I'll close as answered.
We will reflect on all issues at the end of the process to steer future improvements
