### ISSUE TITLE
primaryKey on citation to restrictive?

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#29]
The primary key for the citation table is a combination of id, type and reference. But doesn't that mean that the same target cannot  cite the same paper for 2 different reasons./ways/page numbers?

I got this error when importing a test dataset. In this specific case the 2 rows are identical and doesn't make sense, but they could have in another scenario as far as I can see

```
ERROR:  duplicate key value violates unique constraint "citation_pkey"
DETAIL:  Key (citation_target_id, citation_target_type, citation_reference_id)=(dc4ad29c-1ed3-11e3-bfac-90b11c41863e, ORGANISM, 0b837c5c-6ee1-4d9d-b17e-c9d94e404e01) already exists.
CONTEXT:  COPY citation, line 2375
SQL state: 23505
```

**Comment by timrobertson100** [comment]
I think you are correct.

![image](https://user-images.githubusercontent.com/237221/216615558-10fe904c-3c92-4ef3-b822-52459839be2f.png)

The fix is to add the `citationType` to the PK as well?

**Comment by tucotuco** [comment]
I'm not sure adding citationType to the PK helps either. I think it is feasible to have the same specimen cited twice on a page.

**Comment by timrobertson100** [comment]
I did wonder that but then figured it unlikely to be meaningful given page is the lowest granularity we go to.

I guess then, we add them all to the PK?

**Comment by tucotuco** [comment]
You mean every field? Hardly worth having the PK in that case.

**Comment by timrobertson100** [comment]
It would serve only as a constraint to safeguard against inadvertently filling it with duplicate entries (e.g. if populated as the result of some query in an ETL)
