### ISSUE TITLE
Documentation: clarify what is defined as a GUID

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#31]
Turns out  that we do not all have the same understanding of what a `GUID` is. So it would make sense to clarify what is intended in the documentation.

If I understand correctly, then in this project a `GUID` is anything that can reasonably be argued to be globally unique. For example a URL, ARK or LSID.
https://www.tdwg.org/standards/guid-as/

In this project a GUID doesn't have anything to do with UUIDs (which is described as synonyms of GUIDs in e.g. [wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier))

**Comment by tucotuco** [comment]
@MortenHofft What is the context for the need for this definition? We have the following in the [General considerations section of the Data Mapping document](https://github.com/gbif/model-material/blob/master/data-mapping.md#general-considerations):

"The use of record identifiers for concepts in the UM is ubiquitous, and required whenever you have data that correspond to a given concept. For this exercise, when creating tables in the UM, use resolvable global unique identifiers for the `ID` fields if you have them. If you don't, use non-resolvable global unique identifiers if you have them. If you don't, generate UUIDS as identifiers in place of the identifiers that are unique only within the scope of your database. In cases where your database does not have identifiers for records that can be inferred for the UM, generate UUIDs for these identifiers. For every identifier you have to create in the place of a local one in your database, you CAN also create an `Identifier` record that translates between your local identifier and the one you created for sharing via the UM. If you do this, set the `identifierType` to `local`."

**Comment by MortenHofft** [comment]
It was prompted by my comment in our last meeting, that `http://herbarium.bgbm.org/object/BW00001000` was not a GUID (in the Identifiers table)

@timrobertson100 and I had a discussion afterwards that made me realise that we had very different understanding of what a GUID is. And I was convinced that GUID was a fixed type in the model. I see now that it is simply a free text field in the identifiers table so my comment probably makes less sense. Especially since the section you refer to touch on it - I hadn't seen that. Feel free to close.

**Comment by tucotuco** [comment]
Great. I believe Tim and I have the same understanding about GUIDs. Glad we have something in the doc about what to do in practice. Closing.
