### ISSUE TITLE
specify: agents with null in ID columns

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#32]
I couldn't import agents because:

https://github.com/gbif/model-material/blob/master/specify/Agent/AGENT.csv#L2451
```
ERROR:  null value in column "agent_id" of relation "agent" violates not-null constraint
DETAIL:  Failing row contains (null, person, Benito, Lorenzo ).
CONTEXT:  COPY agent, line 2451: ",person,"Benito, Lorenzo ""
SQL state: 23502
```

Example data snippet
```
95c5a696-d5f3-4b25-b511-86f463679fa1,person,"Ciccotto, Patrick J"
3b3a44dc-3525-4ad2-a85b-e30595dc5be6,person,"Gardner, Andrew"
6c6bfd70-3a8b-4b37-b512-099989178337,person,"Mills-Cook, Marlo"
1587dce2-db96-4b69-bbfb-432daebfeb07,person,"Kinnersly, Margaret"
71ec8dfe-cd13-4185-9fb4-4cb479cfc293,person,"Schragg, Geoff"
526e9a35-95b5-4d84-ada4-33d279a0e1fe,person,"Thomaz, Andrea"
4425b4d5-c1fe-41ca-8949-0bb7d14fab5e,person,"Thayer, M H"
,person,"Benito, Lorenzo "
,person,"Wichman, Katy "
,person,"Hernandez, Mariangeles A"
,person,"Barroso, Diego "
,person,"Casarez, Melissa "
,person,"McInnes, Theresa L"
,person,"Vanderwel, Michelle "
```

**Comment by acbentley** [comment]
These are all georeferencing agents and it appears that GUIDs were not created for them because they were imported using the backend from the Fishnet2 community georeferencing exercise.  I have created UUIDs for all of them and replaced the file.

**Comment by acbentley** [comment]
Doesn't look like I have push access.  Here is the file.
[AGENT.csv](https://github.com/gbif/model-material/files/10668665/AGENT.csv)

**Comment by MortenHofft** [comment]
Thanks, I'v updated the csv. https://github.com/gbif/model-material/commit/9ca291fb46d573dce62daf054897fe1a87aed5ec
