### ISSUE TITLE
specify:citations

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#33]
I couldn't import citations because 

```
ERROR:  invalid input value for enum common_targets: "Organism"
CONTEXT:  COPY citation, line 2, column citation_target_type: "Organism"
SQL state: 22P02
```

changing `Organism` to `ORGANISM` that error is fixed, but then I get
```
ERROR:  duplicate key value violates unique constraint "citation_pkey"
DETAIL:  Key (citation_target_id, citation_target_type, citation_reference_id)=(dc4ad29c-1ed3-11e3-bfac-90b11c41863e, ORGANISM, 0b837c5c-6ee1-4d9d-b17e-c9d94e404e01) already exists.
CONTEXT:  COPY citation, line 2375
SQL state: 23505
```
because the same line appears twice `dc4ad29c-1ed3-11e3-bfac-90b11c41863e,ORGANISM,0b837c5c-6ee1-4d9d-b17e-c9d94e404e01`

I've created an issue here https://github.com/gbif/model-material/issues/29 as I think the schema is too restrictive.
But I also believe it is a mistake in the data as the 2 lines are identical.

**Comment by acbentley** [comment]
Not sure why that line was duplicated.  It is removed in the below.  Can you replace existing file?
[CITATION.csv](https://github.com/gbif/model-material/files/10676424/CITATION.csv)

**Comment by MortenHofft** [comment]
I've replaced the file with the one in https://github.com/gbif/model-material/issues/34#issuecomment-1420945636
Should I just close this issue and ignore this file?

**Comment by acbentley** [comment]
They should be the same so yes.
