### ISSUE TITLE
specify: enum types

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#34]
There is a general issue with case of enum types.

E.g. **citations** use `Organism` instead of `ORGANISM`

```
ERROR:  invalid input value for enum common_targets: "Organism"
CONTEXT:  COPY citation, line 2, column citation_target_type: "Organism"
SQL state: 22P02
```

**digital entity** use `StillImage` instead of `STILL_IMAGE`

**entity**
```
ERROR:  invalid input value for enum entity_type: "MaterialEntity"
CONTEXT:  COPY entity, line 2, column entity_type: "MaterialEntity"
SQL state: 22P02
```

Fixing the type to `MATERIAL_ENTITY` then it works

It seems be a consistent issue that is easily fixed

**Comment by acbentley** [comment]
Attached are new citation and entity tables to fix enum issues
[CITATION.csv](https://github.com/gbif/model-material/files/10676560/CITATION.csv)
[ENTITY.csv](https://github.com/gbif/model-material/files/10676565/ENTITY.csv)
Digital entity has already been fixed and posted
