### ISSUE TITLE
specify: digital entity table

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#36]
Importing this table I get these issues

**First casing**
easily solved by https://github.com/gbif/model-material/issues/34
```
ERROR:  invalid input value for enum digital_entity_type: "StillImage"
CONTEXT:  COPY digital_entity, line 2, column digital_entity_type: "StillImage"
SQL state: 22P02
```

fixing that to be `STILL_IMAGE`

**Second is also casing**
easily solved by https://github.com/gbif/model-material/issues/34
but now get
```
ERROR:  missing data for column "bibliographic_citation"
CONTEXT:  COPY digital_entity, line 2: "a9ffc245-8f88-4b78-a4f4-c559f0b3e8f9,STILL_IMAGE,http://biimages.biodiversity.ku.edu/static/Ichthyol..."
SQL state: 22P04
```

**Missing column**
Adding  a `bibliographic_citation` column and a comma to all rows

now I get

**Third casing again** 
easily solved by https://github.com/gbif/model-material/issues/34
```
ERROR:  invalid input value for enum digital_entity_type: "Text"
CONTEXT:  COPY digital_entity, line 3132, column digital_entity_type: "Text"
SQL state: 22P02
```

changing all `,Text,` to `,TEXT,` will fix that.

**Foreign key constraint**
Now I get 

```
ERROR:  insert or update on table "digital_entity" violates foreign key constraint "digital_entity_digital_entity_id_fkey"
DETAIL:  Key (digital_entity_id)=(a9ffc245-8f88-4b78-a4f4-c559f0b3e8f9) is not present in table "entity".
SQL state: 23503
```

An entry in the entity table with same ID is needed to fix this

https://github.com/gbif/model-material/blob/master/data-mapping.md#7-digitalentities
> For each DigitalEntity, also create an Entity record using the same unique identifier for the entityID as for the digitalEntityID

**Comment by acbentley** [comment]
Here is a new digital_entity file that solves the first three issues
[DIGITAL_ENTITY.csv](https://github.com/gbif/model-material/files/10676505/DIGITAL_ENTITY.csv)

May need to send a new file once I sort out the Morphosource linkages.  I do not have UUIDs for these so will need to create them in post-process.  Do I just add digital_entity_id, digital_entity_type (what type should I use?  MOVING_IMAGE?), and access URI?

**Comment by tucotuco** [comment]
@acbentley It looks like the remaining problem is simple to describe. 

> An entry in the entity table with same ID is needed to fix this
> 
> https://github.com/gbif/model-material/blob/master/data-mapping.md#7-digitalentities
> 
> > For each DigitalEntity, also create an Entity record using the same unique identifier for the entityID as for the digitalEntityID

There are no DigitalEntity records in your Entity.csv.  It only has MaterialEntities. The error is saying that every DigitalEntity records requires a corresponding Entity record. You'll have to add them in the same way you added MaterialEntities.

**Comment by tucotuco** [comment]
> May need to send a new file once I sort out the Morphosource linkages. I do not have UUIDs for these so will need to create them in post-process. Do I just add digital_entity_id, digital_entity_type (what type should I use? MOVING_IMAGE?), and access URI?

It seems to me that the Morphosource linkages are to relationships between some of your collection objects and externally managed digital resources. Is that correct? If so, this seems like a situation where you have no internal Morphosource records _per se_ and you should create `EntityRelationship` records using your collection objects for the `subect_entity_ids`, 'has 3D model' or similar for the `entity_relationship_type`, and the Morphosource link for the `object_entity_iri`.

**Comment by MortenHofft** [comment]
If you have access to the morphosource manifests I think it could be an interesting thing to have in the model data. It is essentially a iiif resource that represents 3d models if I remember correctly? So I suppose it could be a digitalEntity?

**Comment by acbentley** [comment]
Below are a modified ENTITY_RELATIONSHIP file containing the Morphosurce links (at the bottom) as well as the original query results from Specify and the amended file before merging as outlined by @tucotuco above.  If you could drop these all in the entity_relationship folder please?  Let me know if there are any issues.
[ENTITY_RELATIONSHIP.csv](https://github.com/gbif/model-material/files/10686532/ENTITY_RELATIONSHIP.csv)
[entity_relationship_morphosource - original.csv](https://github.com/gbif/model-material/files/10686533/entity_relationship_morphosource.-.original.csv)
[entity_relationship_morphosource.csv](https://github.com/gbif/model-material/files/10686534/entity_relationship_morphosource.csv)

**Comment by acbentley** [comment]
Also, here is a new ENTITY.csv file with all ditgiral_entities added as requested above
[ENTITY.csv](https://github.com/gbif/model-material/files/10686564/ENTITY.csv)
