### ISSUE TITLE
specify: relationships

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#38]
during import i get

```
ERROR:  missing data for column "entity_relationship_date"
CONTEXT:  COPY entity_relationship, line 2: "dcc004bd-1ed3-11e3-bfac-90b11c41863e,shown in,a9ffc245-8f88-4b78-a4f4-c559f0b3e8f9,,,"
SQL state: 22P04
```

I assume the import fails because 2 columns are missing
schema: https://github.com/gbif/model-material/blob/master/schema.sql#L431

I do not see these
```
entity_relationship_id TEXT PRIMARY KEY,
depends_on_entity_relationship_id TEXT REFERENCES entity_relationship ON DELETE CASCADE,
```

**Comment by acbentley** [comment]
Not sure what should be in these two columns.  Can someone explain?

**Comment by acbentley** [comment]
I have added them but they are currently blnak

**Comment by MortenHofft** [comment]
> I have added them but they are currently blank

I think you forgot to send the updated version?

**Comment by acbentley** [comment]
I was waiting to hear what was supposed to be in those columns if anything.

Andy

    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V
Andy Bentley
Ichthyology Collection Manager
University of Kansas
Biodiversity Institute
Dyche Hall
1345 Jayhawk Boulevard<x-apple-data-detectors://9/>
Lawrence, KS, 66045-7561<x-apple-data-detectors://9/>
USA<x-apple-data-detectors://9/>

Tel: (785) 864-3863<tel:%28785%29%20864-3863>
Fax: (785) 864-5335<tel:%28785%29%20864-5335>
Email: ***@***.******@***.***>
ORCID: https://orcid.org/0000-0002-3093-1258<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Forcid.org%2F0000-0002-3093-1258&data=04%7C01%7Cabentley%40ku.edu%7C5720c0e4d0f94b9e0df008da0127752c%7C3c176536afe643f5b96636feabbe3c1a%7C0%7C0%7C637823566221065460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LFnPbiFA9HMZ8k85%2F0%2FOx5vJxTNhZTjAo7S%2BqrDAh6c%3D&reserved=0>
http://ichthyology.biodiversity.ku.edu<http://ichthyology.biodiversity.ku.edu/>
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V


From: Morten Høfft ***@***.***>
Reply-To: gbif/model-material ***@***.***>
Date: Thursday, February 9, 2023 at 9:10 AM
To: gbif/model-material ***@***.***>
Cc: Andrew Bentley ***@***.***>, Comment ***@***.***>
Subject: Re: [gbif/model-material] specify: relationships (Issue #38)


I have added them but they are currently blank

I think you forgot to send the updated version?

**Comment by tucotuco** [comment]
> Not sure what should be in these two columns. Can someone explain?

@acbentley  The field entity_relationship_id is a primary key for the table. I don't think you have relationship identifiers in Specify, so these need to be generated after export.

The depends_on_relationship_id is a foreign key that points to a parent relationship upon which the current relationship depends. Since you won't have relationship identifiers, I don't think you'll have any dependencies either, so all of the values in this field for your data would be blank.

**Comment by acbentley** [comment]
OK, below is amended entity_relationship file with entity_relationship_id added in the same way as for georeference with the following Excel formula:

=LOWER(CONCATENATE(DEC2HEX(RANDBETWEEN(0,4294967295),8),"-",DEC2HEX(RANDBETWEEN(0,65535),4),"-",DEC2HEX(RANDBETWEEN(0,65535),4),"-",DEC2HEX(RANDBETWEEN(0,65535),4),"-",DEC2HEX(RANDBETWEEN(0,4294967295),8),DEC2HEX(RANDBETWEEN(0,65535),4)))

[ENTITY_RELATIONSHIP.csv](https://github.com/gbif/model-material/files/10709207/ENTITY_RELATIONSHIP.csv)

**Comment by tucotuco** [comment]
This also generated distinct UUID-formatted strings. Should be good. @MortenHofft will tell us if there are any remaining issues.
