### ISSUE TITLE
specify: georeference

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#40]
i cannot import georeferences

```
ERROR:  null value in column "georeference_id" of relation "georeference" violates not-null constraint
DETAIL:  Failing row contains (null, ca4b779b-2f6f-4573-9675-65a068103b50, 35.3457, -94.4535, WGS84, null, null, null, null, null, null, null, null, null, GEOLocate, null, null).
CONTEXT:  COPY georeference, line 2: ",ca4b779b-2f6f-4573-9675-65a068103b50,35.3457,-94.4535,WGS84,,,,,,,,,,GEOLocate,,"
SQL state: 23502
```

I also notice that the header looks odd
`"2,123-geocoorddetails.geocoorddetail.text1",location_id,decimal_latitude,decimal_longitude,geodetic_datum,coordinate_uncertainty_in_meters,coordinate_precision,point_radius_spatial_fit,footprint_wkt,footprint_srs,footprint_spatial_fit,georeferenced_by,georeferenced_date,georeference_protocol,georeference_source,georeference_remarks,preferred_spatial_representation
`

**Comment by MortenHofft** [comment]
@tucotuco could you advice please

**Comment by tucotuco** [comment]
@acbentley Though there is a one-to-zero-or-one correspondence between georeferences and locations in your data, and using the locationID for the georeferenceID would actually work in a database defined by schema.sql, Location is a class distinct from Georeference in the Unified Model. To use the locationID for the georeferenceID would incorrectly suggest that a Georeference IS A Location, which isn't the case. Best practice would be to provide UUIDs in post-processing for the georeferences.

**Comment by acbentley** [comment]
OK, below is georeference file with georeference_id added.  I used the following formula in Excel to generate UUIDs for them.  Hope they are indeed unique:

=LOWER(CONCATENATE(DEC2HEX(RANDBETWEEN(0,4294967295),8),"-",DEC2HEX(RANDBETWEEN(0,65535),4),"-",DEC2HEX(RANDBETWEEN(0,65535),4),"-",DEC2HEX(RANDBETWEEN(0,65535),4),"-",DEC2HEX(RANDBETWEEN(0,4294967295),8),DEC2HEX(RANDBETWEEN(0,65535),4)))

[GEOREFERENCE.csv](https://github.com/gbif/model-material/files/10709169/GEOREFERENCE.csv)

**Comment by tucotuco** [comment]
@acbentley Though that is not a rigorous UUID generation schema, it generated values that are distinct within your data, so that will work. Thanks.
