### ISSUE TITLE
specify: taxon

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#41]
I cannot import taxon csv

```
ERROR:  missing data for column "taxon_remarks"
CONTEXT:  COPY taxon, line 2: "92101c21-9e58-11ed-803c-6c2b597b15e2,Animalia,,,,Kingdom,,"
SQL state: 22P04
```

I guess it is because the `scientific_name_id` column is missing

**Comment by acbentley** [comment]
Columns added - also added parent_taxon_id and taxonomic_status columns that were also missing
[TAXON.csv](https://github.com/gbif/model-material/files/10698303/TAXON.csv)
