### ISSUE TITLE
specify: identifications

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#42]
I cannot import identifications

```
ERROR:  null value in column "identification_type" of relation "identification" violates not-null constraint
DETAIL:  Failing row contains (de3c7481-1ed3-11e3-bfac-90b11c41863e, db8a709d-1ed3-11e3-bfac-90b11c41863e, null, null, Lepisosteus platostomus, null, Cross, Frank B, ca49cfbc-3e8f-48ce-87e3-058295d344dc, null, null, null, null, null, null).
CONTEXT:  COPY identification, line 2: "de3c7481-1ed3-11e3-bfac-90b11c41863e,db8a709d-1ed3-11e3-bfac-90b11c41863e,,,Lepisosteus platostomus,..."
SQL state: 23502
```

I notice that there are not `identification_type` provided and it is a NOT NULL column https://github.com/gbif/model-material/blob/master/schema.sql#L293

**Comment by tucotuco** [comment]
@acbentley Arctos has a "nature of identification" [controlled vocabulary](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctnature_of_id) for values that might work well here.

**Comment by acbentley** [comment]
We do not have anything similar in Specify so I have just entered "unknown" for all in the below
[IDENTIFICATION.csv](https://github.com/gbif/model-material/files/10698260/IDENTIFICATION.csv)
