### ISSUE TITLE
specify: genetic sequences

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#44]
genetic sequence table requires a sequence
https://github.com/gbif/model-material/blob/master/schema.sql#L245

but there is none
54869bf6-a0b5-11ed-803c-6c2b597b15e2,KM207619,

so the import fails
```
ERROR:  null value in column "sequence" of relation "genetic_sequence" violates not-null constraint
DETAIL:  Failing row contains (54869bf6-a0b5-11ed-803c-6c2b597b15e2, KM207619, null).
CONTEXT:  COPY genetic_sequence, line 2: "54869bf6-a0b5-11ed-803c-6c2b597b15e2,KM207619,"
SQL state: 23502
```

**Comment by acbentley** [comment]
Can someone give me an idea of what the genetic_sequence_type and sequence fields should contain?  The KM207619 is the sequence ID from Genbank.  I do not have the actual sequence in my database.

**Comment by MortenHofft** [comment]
@tucotuco can you help here please

**Comment by tucotuco** [comment]
@MortenHofft @acbentley Given that the source database does not have the sequences, there should not be any GeneticSequence records. Instead, the sequences should be linked via the EntityRelationship table using the object_entity_iri, using the URL to the Genbank Accession for content. So, a record might look like this:

entity_relationship_id, depends_on_entity_relationship_id, subject_entity_id, entity_relationship_type, object_entity_id, object_entity_iri, entity_relationship_date, entity_relationship_order

some_entity_relationship_guid, , '54869bf6-a0b5-11ed-803c-6c2b597b15e2', 'has genetic sequence', , 'https://www.ncbi.nlm.nih.gov/nuccore/KM207619', , 1

**Comment by MortenHofft** [comment]
Could we use `HAS DNA SAMPLE` - that is what @jholetschek is using. Just to make my life easier.

**Comment by tucotuco** [comment]
For sure!

**Comment by acbentley** [comment]
File below has genetic sequences with links (object_entity_iri) and entity_relationship_type as "has genetic sequence".  Given this I think we can delete the genetic sequence folder?
[ENTITY_RELATIONSHIP.csv](https://github.com/gbif/model-material/files/10724207/ENTITY_RELATIONSHIP.csv)

**Comment by MortenHofft** [comment]
I look forward to those vocabularies of possible relation types (and other types) :)

@acbentley I will close this issue then in favour of #55 - else i do not know what files to use.

**Comment by MortenHofft** [comment]
Does that mean that the [genetic sequence folder](https://github.com/gbif/model-material/tree/master/specify/Genetic_sequence) should be deleted/disregarded @acbentley ?

**Comment by acbentley** [comment]
Yes, I would think so. @tucotuco can you confirm?

**Comment by tucotuco** [comment]
Confirmed.
