### ISSUE TITLE
specify: taxon identification

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#47]
`taxon_confidence_percent` is a required field but not in the CSV. So the import fails. 
But it has been decided that the field should be removed completely. https://github.com/gbif/model-material/issues/46

I have removed it, but that also means that it should be removed from the CSV export

**Comment by acbentley** [comment]
That field was not mapped and was added in post-process.  I have removed it in the below
[TAXON_IDENTIFICATION.csv](https://github.com/gbif/model-material/files/10698171/TAXON_IDENTIFICATION.csv)
