### ISSUE TITLE
specify: agent role

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#49]
```
ERROR:  duplicate key value violates unique constraint "agent_role_pkey"
DETAIL:  Key (agent_role_target_id, agent_role_target_type, agent_role_agent_id, agent_role_order)=(db930470-1ed3-11e3-bfac-90b11c41863e, ORGANISM, 90ddcd29-5977-4b06-9288-dfe1724729bb, 1) already exists.
CONTEXT:  COPY agent_role, line 75051
SQL state: 23505
```

@tucotuco That looks to me to be a mistake in the schema constraints
https://github.com/gbif/model-material/blob/master/schema.sql#L609

why would there be a primary key on `PRIMARY KEY (agent_role_target_id, agent_role_target_type, agent_role_agent_id, agent_role_order)` shouldn't it say `agent_role_role` instead of `agent_role_order` perhaps?

possibly even include `agent_role_began and agent_role_ended`? in case someone worked on the same specimen with the same role in 2 periods?

**Comment by tucotuco** [comment]
@MortenHofft The primary key should indeed include agent_role_role. On further reflection, I think the primary key has to include every field. In addition to the begin and end of the role, the Agent might be specified only by a name, and not an agent_id. I have modified the constraint in [this commit](d9b6b3b328f218abadecc7935aae57e684312aed). With that change @acbentley should not have to make any modifications to his data.

**Comment by MortenHofft** [comment]
invalid schema @tucotuco I assume that should be `agent_role_ended`. I will change it. Let me know if you disagree.

```
ERROR:  column "agent_role" named in key does not exist
LINE 609:   PRIMARY KEY (agent_role_target_id, agent_role_target_type,...
```

**Comment by tucotuco** [comment]
Yes, thank you @MortenHofft .

**Comment by MortenHofft** [comment]
Using the new schema I get this error in when loading the data

run
```
COPY public.agent_role(agent_role_target_id,agent_role_target_type,agent_role_agent_id,agent_role_agent_name,agent_role_role,agent_role_began,agent_role_ended,agent_role_order)
FROM '/Users/UserName/Documents/dev/git/gbif/model-material/specify/Agent_role/AGENT_ROLE.csv' 
DELIMITER ',' 
CSV HEADER;
```

error
```
ERROR:  null value in column "agent_role_began" of relation "agent_role" violates not-null constraint
DETAIL:  Failing row contains (dbc8da3a-1ed3-11e3-bfac-90b11c41863e, ORGANISM, ca49cfbc-3e8f-48ce-87e3-058295d344dc, Cross, Frank B, collector, null, null, 1).
CONTEXT:  COPY agent_role, line 2: "dbc8da3a-1ed3-11e3-bfac-90b11c41863e,ORGANISM,ca49cfbc-3e8f-48ce-87e3-058295d344dc,"Cross, Frank B",..."
SQL state: 23502
```

**Comment by tucotuco** [comment]
Hmm, I don't see a NOT NULL constraint on agent_role_began. Is that by virtue of being part of the primary key? If so, we have to remove the began and ended from the primary key.

**Comment by MortenHofft** [comment]
@tucotuco 
should the agent_role table then look like this instead

```
CREATE TABLE agent_role (
  agent_role_target_id TEXT NOT NULL,
  agent_role_target_type COMMON_TARGETS NOT NULL,
  agent_role_agent_id TEXT REFERENCES agent ON DELETE CASCADE,
  agent_role_agent_name TEXT,
  agent_role_role TEXT,
  agent_role_began TEXT,
  agent_role_ended TEXT,
  agent_role_order SMALLINT NOT NULL CHECK (agent_role_order >= 0) DEFAULT 0
);
CREATE INDEX ON agent_role(agent_role_target_type);
ALTER TABLE agent_role ADD CONSTRAINT agent_role_unique_key UNIQUE (agent_role_target_id, agent_role_target_type, agent_role_agent_id, agent_role_agent_name, agent_role_role, agent_role_began, agent_role_ended, agent_role_order);
```

**Comment by tucotuco** [comment]
@MortenHofft Yes. Will you update that or would you rather I do it?
