### ISSUE TITLE
bgbm: event type for occurrences

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#53]
I just realized we gave specific guidance in the [Occurrence and Other Events section](https://github.com/gbif/model-material/blob/master/data-mapping.md#12-occurrences-and-other-events) of the Mapping for Events that are Occurrences:

Each Occurrence has its own occurrenceID. The Occurrences associated with a given Organism can be discovered by the organismID they have in common. Every Occurrence must have a corresponding Event record in which the eventID is the same is the occurrenceID and the eventType for the Event record MUST be OCCURRENCE.

_Originally posted by @tucotuco in https://github.com/gbif/model-material/issues/52#issuecomment-1425833632_

**Comment by MortenHofft** [comment]
@jholetschek that sounds like you should update that type as well? I believe you use `GATHERING`

**Comment by jholetschek** [comment]
Wow! ❤️❤️❤️
Thanks, Morten!

**Comment by jholetschek** [comment]
Yes, will do.

This will correct the BGBM data in Postgres:

update event
set event_type='OCCURRENCE'
where event_type='GATHERING'
