### ISSUE TITLE
specify: citations

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#54]
ERROR:  null value in column "citation_page_number" of relation "citation" violates not-null constraint
DETAIL:  Failing row contains (dbef348e-1ed3-11e3-bfac-90b11c41863e, ORGANISM, db876f1b-b573-4144-9487-5d96ef8a7a0e, JOURNAL_ARTICLE, null, null).
CONTEXT:  COPY citation, line 2: "dbef348e-1ed3-11e3-bfac-90b11c41863e,ORGANISM,db876f1b-b573-4144-9487-5d96ef8a7a0e,JOURNAL_ARTICLE,,"
SQL state: 23502

**Comment by acbentley** [comment]
I don't have any citation page numbers.  Why is this a required field?

**Comment by MortenHofft** [comment]
I suspect it was unintended and the intention was to ensure that no 2 entries were identical (nulls included)
See #29
@tucotuco correct me if I'm wrong

**Comment by tucotuco** [comment]
That is correct, another unintended side effect of a primary key where one of the fields can contain Null values.

In PostgreSQL, a primary key constraint enforces the requirement for unique values across all columns listed in the constraint. However, by default, a NULL value is treated as distinct from all other values, including other NULL values. This means that two rows can have the same values for all columns in the primary key constraint, as long as one of them has a NULL value for citation_page_number and the other has a non-NULL value.

To enforce the requirement that the combination of all columns in the primary key constraint must be unique, even if one or more of them are NULL, we have to instead create a unique constraint and remove the PRIMARY KEY:

`ALTER TABLE citation ADD CONSTRAINT citation_unique_key UNIQUE (citation_target_id, citation_target_type, citation_reference_id, citation_type, citation_page_number, citation_remarks);`

This will ensure that no two rows in the citation table have the same values for the columns listed in the unique constraint, even if one or more of the values is NULL.

I have made this change in [this commit](582b183a2872b9e0d6e0a81e57104693a96ff6f0).

**Comment by acbentley** [comment]
So, nothing I need to do here?

**Comment by tucotuco** [comment]
@acbentley Not yet anyway. @MortenHofft can try to import the file with this new constraint and see how it goes.

**Comment by MortenHofft** [comment]
works now 🎉
