### ISSUE TITLE
specify: entity relationships

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#55]
ERROR:  null value in column "entity_relationship_order" of relation "entity_relationship" violates not-null constraint
DETAIL:  Failing row contains (a6f692c9-d321-9f67-7b85-f821911b9d37, null, dcc004bd-1ed3-11e3-bfac-90b11c41863e, shown in, a9ffc245-8f88-4b78-a4f4-c559f0b3e8f9, null, null, null).
CONTEXT:  COPY entity_relationship, line 2: "a6f692c9-d321-9f67-7b85-f821911b9d37,,dcc004bd-1ed3-11e3-bfac-90b11c41863e,shown in,a9ffc245-8f88-4b..."
SQL state: 23502

**Comment by MortenHofft** [comment]
For now you can just set them all to zero I assume. But ideally it would behave as @tucotuco intended

**Comment by acbentley** [comment]
OK, done in below
[ENTITY_RELATIONSHIP.csv](https://github.com/gbif/model-material/files/10724416/ENTITY_RELATIONSHIP.csv)

**Comment by MortenHofft** [comment]
the schema says that the `entity_relationship_id`s must be unique. But e.g. `db46a51c-1ed3-11e3-bfac-90b11c41863e` is being reused 4 times.

**Comment by acbentley** [comment]
The way I have been creating these is that the entity_relationship_id is the collection object GUID and the subject_entity_id is the image/sequence/morphosource GUID.  They will be duplicated based on how many images etc. point at the same collection object.  Is that not correct? @tucotuco

**Comment by tucotuco** [comment]
@acbentley No, that is not correct. The entity_relationship_id is a unique primary key for the entity_relationship table. It is one of those fields that has be have UUIDs generated. The subject_entity_id (the entity on the "left" side of the relationship in subject isRelatedTo object) should be the collection object id. The object of the relationship is the object_entity_id filled with the digital_entity_id of the Morphosource digital_entity (if you have Morphosource records as digital_entities) or the object of the relationship is the object_entity_iri filled with the Morphosource URL (if you don't have Morphosource records as digital_entities). The latter is similar to the Genetic Sequence scenario where the objects of the relationship are external accessed by a URL.
So, the subject_entity_id will be the one that repeats, not the entity_relationship_id, which MUST be unique.

**Comment by acbentley** [comment]
Arrrggg!!  Of course.  Again, I forgot that step when I recreated the file upon re-entering the sequence information.  Corrected file below

[ENTITY_RELATIONSHIP.csv](https://github.com/gbif/model-material/files/10725973/ENTITY_RELATIONSHIP.csv)

**Comment by MortenHofft** [comment]
It worked! 🎉
