### ISSUE TITLE
specify: georeference

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#57]
ERROR:  null value in column "decimal_latitude" of relation "georeference" violates not-null constraint
DETAIL:  Failing row contains (7e49a581-afc7-2189-2aff-8d67ad506987, d32e1a0a-b339-4b8d-9fae-f01f40636c32, null, null, WGS84, null, null, null, null, null, null, null, null, null, null, null, null).
CONTEXT:  COPY georeference, line 50: "7e49a581-afc7-2189-2aff-8d67ad506987,d32e1a0a-b339-4b8d-9fae-f01f40636c32,,,WGS84,,,,,,,,,,,,"
SQL state: 23502

**Comment by acbentley** [comment]
OK, so lat and long fields cannot be null.  There are a number of these.  I have amended the Specify query to restrict lat and long to not be empty.  I have removed all empty lat and long lines in the below.
[GEOREFERENCE.csv](https://github.com/gbif/model-material/files/10723945/GEOREFERENCE.csv)

**Comment by MortenHofft** [comment]
I cannot validate the file as it depends on the location table, but will close this issue for now

**Comment by MortenHofft** [comment]
The location table is now in place. But I now get issues with the georeference table

```
ERROR:  insert or update on table "georeference" violates foreign key constraint "georeference_location_id_fkey"
DETAIL:  Key (location_id)=(abfc26f6-d547-43d9-82bd-2a63fdb2d9eb) is not present in table "location".
SQL state: 23503
```

the georeference table refers to a location ID `abfc26f6-d547-43d9-82bd-2a63fdb2d9eb` which isn't in the location table
