### ISSUE TITLE
specify: question on occurrences

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#60]
@tucotuco this might be a question for you and not @acbentley 

> Context:  I'm trying to reconstruct a single specimen https://www.gbif.org/occurrence/657029235
which I believe is the same as dc96c974-1ed3-11e3-bfac-90b11c41863e in the data we have in this repo. And I think this is the specify version: https://ichthyology.specify.ku.edu/specify/view/collectionobject/34592/

I'm currently try to get at the location.

I can see that in line 7899 in the GEOREFENCE file those coordinates I see on GBIF.org appears.
So it is in there apparently. But I would expect it to be linked to an occurrence with the entity as evidence.

Currently what I have been doing is to take an occurrence. I do not know which i ought to take, so I just take one. And from there i take the event and from that the location and then the georeference.

But in the specify case the `occurrence_evidence` table is empty.

Is that expected? And secondly what is the recommended way to get the coordinates (of the gathering/collecting event I assume is what most people is interested in)

**Comment by tucotuco** [comment]
@MortenHofft @acbentley Andy has made Events that have the Occurrence subtype. Now the corresponding Occurrence records need to be created using the same event_ids and connecting the Occurrences to the collection objects (organism table). The Occurrence table has many of the terms familiar from the Occurrence class in Darwin Core.
The OccurrenceEvidence table is a way to declare specifically on which MaterialEntities and/or DigitalEntities the assertion of the Occurrence of the Organism was based. In Andy's case there are only collection objects declared (MaterialEntities at the level of the Organism). If Andy has Occurrences whose evidence is captured in images, video, or other DigitalEntities, he could populate the OccurrenceEvidence table to connect them.

So, with the Occurrence table in place, there should be a complete chain from collection objects to their locations - Organism to Occurrence (occurrence.organism_id=organism.organism_id), Occurrence to Event (occurrence.occurrence_id=event.event_id), Event to Location (event.location_id=location.location_id), Location to Georeference (location.accepted_georeference_id=georeference.georeference_id).  You should not need OccurrenceEvidence to make this association.

**Comment by MortenHofft** [comment]
> Now the corresponding Occurrence records need to be created using the same event_ids and connecting the Occurrences to the collection objects (organism table). 

So does that mean that the `occurrence` table **should** be filled by @acbentley ?

And that he could **choose** to fill the `OccurrenceEvidence` table. What counts as evidence? Is that only digital entities?

**Comment by tucotuco** [comment]
Yes, the Occurrence table MUST be filled in as the Event table references them, and they do not currently exist. They'll have occurrence_ids equal to the event_ids in their parent records in the Event table.


And yes, he could fill in the OccurrenceEvidence table. Any Entity can be Evidence, including the Organisms he has already created. OccurrenceEvidence records could be made using the Organisms, but that evidence would be no more specific than is already expressed in the relationship occurrence.organism_id. In that sense it would just be redundant.

**Comment by acbentley** [comment]
So, if I am reading this correctly, I need an occurrence file that would have occurrence_id = collecting event GUID and organism_id as CO GUID along with any of the additional fields I can fill in?  Looks like the only field that is not null is occurrence_status which I will need to fill in as present through post-process.  So, something like this:

[OCCURRENCE.csv](https://github.com/gbif/model-material/files/10735736/OCCURRENCE.csv)

**Comment by MortenHofft** [comment]
```
ERROR: null value in column "occurrence_id" of relation "occurrence" violates not-null constraint
  Detail: Failing row contains (null, db1e98b0-1ed3-11e3-bfac-90b11c41863e, 1, null, null, null, null, null, null, PRESENT, null, null, null, null, null, null, null, 6381a8e5-449e-4ac5-a21e-c09f69fda36a, null, null, null).
  Where: COPY occurrence, line 463: ",db1e98b0-1ed3-11e3-bfac-90b11c41863e,1,,,,,,,PRESENT,,,,,,,,6381a8e5-449e-4ac5-a21e-c09f69fda36a,,,"
```

Looks like there is a new line issue perhaps?

line 11625
`2 - 5 specimens`

**Comment by acbentley** [comment]
Looks like it is a line break issue.  There is not much important information in that field so I have just removed the contents.

[OCCURRENCE.csv](https://github.com/gbif/model-material/files/10735869/OCCURRENCE.csv)

**Comment by MortenHofft** [comment]
There are still rows without IDs (line 38170)

```
41c3831e-f5eb-4bca-87b6-47df9e651375,dcbdb73a-1ed3-11e3-bfac-90b11c41863e,1,,,,,,,PRESENT,,,,,,,,046aa9ac-00aa-46c3-8f83-39fd27f45023,,,
,dcbdb88d-1ed3-11e3-bfac-90b11c41863e,1,,,,,,,PRESENT,,,,,,,,6381a8e5-449e-4ac5-a21e-c09f69fda36a,,,
```

**Comment by acbentley** [comment]
Those are all collection objects that do not have collecting events.  Looks like there are 12 of them but not sure why they are missing.  I will investigate and then upload a new file with the fix.

**Comment by acbentley** [comment]
OK, occurrence has been corrected.  There were two specimens that did not have collecting events and I cannot find the specimens so I just deleted them for now.

[OCCURRENCE.csv](https://github.com/gbif/model-material/files/10736964/OCCURRENCE.csv)

**Comment by MortenHofft** [comment]
```
SQL Error [23505]: ERROR: duplicate key value violates unique constraint "occurrence_pkey"
  Detail: Key (occurrence_id)=(ffea0498-4993-4698-a54b-cbe5e11727a4) already exists.
  Where: COPY occurrence, line 4
```

Example: `occurrence_id:ffea0498-4993-4698-a54b-cbe5e11727a4` is used 6 times

**Comment by acbentley** [comment]
That is because there are 6 specimens that have the same collecting event.  Am I misunderstanding something here?  I thought this file was meant to link collection object records (organism_id) to collecting event records (occurrence_id)?  Due to the 1:M nature of collection objects to collecting events, occurrence_id will not be unique.

**Comment by tucotuco** [comment]
@acbentley Your collecting events, in which many specimens were collected, are parent Events to the Occurrences, which are also Events, but at the level of the Organisms. Thus, your collecting event ids are at a level below where they should be. 

You already exported Event records for the collecting events in your database. You need Event records for your Occurrences, because they are also Events. The Occurrences are not collecting Events, they are "Organisms at a place and time". Thus, each of your collection objects corresponds to an Occurrence with an occurrence_id you'll have to generate, because you don't have those in your database (your collection_object_ids are used for Organisms, which are MaterialEntities, not Events). That ought to take care of the Occurrence table, but you will need to create the Event records corresponding to those Occurrences and add them to Event.csv. For those Occurrence-based Events you will have event.event_id=occurrence.occurrence_id, and you'll have event.parent_event_id=[your corresponding existing collecting event id]. This will make for no duplication in the Occurrence table and put the one-to-many relationship you are talking about in the event.parent_event_id.

I hope that makes sense. Another way to think of it that might be helpful is, suppose you published your collecting_event_ids in the Darwin Core eventID field ( might actually do that, I don't know). Your Occurrences could then be grouped by the eventID. That would be your one-to-many relationship. But you have occurrenceIDs distinct for those - one for each specimen. That part is the same here in the Unified Model. The tricky part is that an Occurrence is an Event with an occurrenceID that is an eventID, not a MaterialEntity with an occurrenceID that is a materialEntityID.

**Comment by acbentley** [comment]
OK, here is the corrected occurrence file with occurrence_id created as in other tables
[OCCURRENCE.csv](https://github.com/gbif/model-material/files/10748012/OCCURRENCE.csv)

For the event file, I have added the corresponding fields to event_id (occurrence_id) and parent_event_id (event_id) in the below along with the dataset_id but what do I enter for the rest of the fields if anything?

[EVENT.csv](https://github.com/gbif/model-material/files/10748043/EVENT.csv)

**Comment by tucotuco** [comment]
> For the event file, I have added the corresponding fields to event_id (occurrence_id) and parent_event_id (event_id) in the below along with the dataset_id but what do I enter for the rest of the fields if anything?

Everything that applies, In your case, all of the same information that is in the parent Event.

**Comment by acbentley** [comment]
Surely that can be gleaned from the original occurrence record that is already there and doesn't need to be duplicated?  It is going to be non-trivial for me to make the connection between the collecting event ids I have just added (and their corresponding occurrence_ids that I created) and the existing collecting event IDs

**Comment by tucotuco** [comment]
No information will be lost, for sure. The parent Events will have it all. It is just a matter of how easy it is to access it. You said, "can be gleaned from the original occurrence record." The information we're talking about isn't in Occurrence records (e.g., no location_id, no event_date, etc.), but rather in the Event records that are the parents of the Occurrences. I can see that if you generate the Occurrence record alone and then given them occurrence_ids _post facto_, then it would be hard to connect the two. However, if you generate records that are a combination of all of the Occurrence and Event fields, then split those records into the parts that go into each destination, you have the connection - the occurrence_id with all of the Occurrence fields into the Occurrence.csv and the occurrence_id (as event_id) with all of the Event fields into the Event.csv file.

**Comment by acbentley** [comment]
Tough to do that without causing similar duplication issues across the collection object, collecting event, locality tables I wouldn't think.  My head hurts thinking about it.  So, for now I think I will leave it as is if that is OK.

**Comment by tucotuco** [comment]
@MortenHofft, as the one trying to make sense of things in a UI, has final say right now. If we implement the suggested constraint, the deduplication will have to occur.

**Comment by MortenHofft** [comment]
I'm closing this and other issues as it isn't a data issue in terms of wether it is valid or not. Which is why why this and others were created. Also data has changed alot since, so it hardly makes sense to keep them open
