### ISSUE TITLE
specify: genetic sequences and digital entities

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#62]
I see lines like this in the digital entities file
`5475a6d2-a0b5-11ed-803c-6c2b597b15e2,GENETIC_SEQUENCE,https://www.ncbi.nlm.nih.gov/nuccore/HE863811,,,,,,,,,,,,,,`

Does it make sense to have a digital_entity of type GENETIC_SEQUENCE without a corresponding entry in the genetic_sequences table?

And if not are there then any point in creating a digital entity and corresponding entity in the first instance?

Shouldn't the material entity just have the relation `has genetic sequence` instead?  currently we create a relation from the material to a new entity, that has a digital entity of type genetic. And that entity has a relation of type `has genetic sequence`.

**Comment by acbentley** [comment]
This goes to the conversation with @tucotuco about me not actually having the sequence but simply a link to a Genbank sequence.  As such no genetic_sequence exists in my database and this is simply an entity_relationship to an external entity.

**Comment by MortenHofft** [comment]
I believe this can be closed in favour of #68
