### ISSUE TITLE
Specify: events are lonely

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#64]
Events seem detached from everything else
E.g. the first one `7f034432-c814-4d6d-9ed7-64ff5dff6338` in https://github.com/gbif/model-material/blob/master/specify/Event/EVENT.csv

How is that related to other entries?

**Comment by acbentley** [comment]
I think this is because events are shared across collections in Specify, some of these events may relate to objects in other collections (tissues or observations and thus may not link to anything currently.

**Comment by MortenHofft** [comment]
Do you have an example of a not detached event? I thought events was only linked via occurrences and that table isn't filled so hence my confusion.

**Comment by tucotuco** [comment]
This is the same issue with the missing Occurrence records for the corresponding Events that have event_type 'OCCURRENCE'.

It is feasible to have Events that are not Occurrences, such as trawls, expeditions, and other parent Events of Occurrences.

**Comment by MortenHofft** [comment]
Okay so it is possible for me to share that a trawl took place, but there was no occurrences for it. I suppose that makes sense (for cases that aren't specimens). But in this specific case, those events need corresponding occurrences to make sense. 
Thanks

**Comment by MortenHofft** [comment]
close as this will be fixed by https://github.com/gbif/model-material/issues/60
