### ISSUE TITLE
Specify: assertions

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#65]
> Context:  I'm trying to reconstruct a single specimen https://www.gbif.org/occurrence/657029235
which I believe is the same as dc96c974-1ed3-11e3-bfac-90b11c41863e in the data we have in this repo. And I think this is the specify version: https://ichthyology.specify.ku.edu/specify/view/collectionobject/34592/

Looking at https://ichthyology.specify.ku.edu/specify/view/collectionobject/34592/
i notice that there is a size: `346mm SL`

I couldn't find that in the data exported. I might well have missed it, but if not then that seem like a candidate to put into the assertions table linked to the material entity?

**Comment by tucotuco** [comment]
Yes, that looks like an Assertion about the Organism at the time the measurement was taken.

**Comment by acbentley** [comment]
OK, I just created the below file.  I used ORGANISM as the assertion_target_type and LENGTH as the assertion_type.  Similar files could be created for other assertions in Specify and would need to be stitched together.  Assertions are what we would call CO attributes which are found in a 1:1 relationship to COs.
[ASSERTION.csv](https://github.com/gbif/model-material/files/10733757/ASSERTION.csv)

**Comment by MortenHofft** [comment]
I get
```
ERROR: null value in column "assertion_id" of relation "assertion" violates not-null constraint
  Detail: Failing row contains (null, db8bec9e-1ed3-11e3-bfac-90b11c41863e, ORGANISM, null, LENGTH, null, null, 192mm SL, null, null, null, null, null, null, null).
  Where: COPY assertion, line 2: ",db8bec9e-1ed3-11e3-bfac-90b11c41863e,ORGANISM,,LENGTH,,,192mm SL,,,,,,,"
```

**Comment by tucotuco** [comment]
Another situation where GUIDs need to be generated where they did not exist in the original data (unless @acbentley has GUIDs on the collection_object_attributes themselves).

**Comment by acbentley** [comment]
That's what I get for trying to do multiple things at once.  Forgot that step again of creating GUIDs.  Done in the below
[ASSERTION.csv](https://github.com/gbif/model-material/files/10734890/ASSERTION.csv)
