### ISSUE TITLE
Specify: reverse image relationships

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#67]
This is more of a service to me
But since there are not relationships of type "shown in", that also has values in `object_entity_iri` it should be safe to reverse the relationship.

```sql
/* no results */
select count(*) from entity_relationship
where entity_relationship_type = 'shown in' and object_entity_iri is not null  
```

So we could reverse the relationship and change the type to `IMAGE OF`, which would make it consistent with BGBM.

```sql
update entity_relationship
set entity_relationship_type = 'IMAGE OF',
    object_entity_id = subject_entity_id,
    subject_entity_id  = object_entity_id 
where entity_relationship_type ='shown in'
```
Am I correct in assuming it is unproblematic?
Is that feasible for you to do @acbentley ? 

I can also just run it, but it is nicer to have it in your export

**Comment by acbentley** [comment]
If I read this correctly it is simply a case of reversing the two id columns and changing the relationship type (which wad done in post-process anyway).  If that is the case, then yes, that should be fairly easy to accomplish.

**Comment by tucotuco** [comment]
@acbentley Yes, that is all that would be required to have the relationship in the order that matched what BGBM did. Note that there is a [Discourse topic](https://discourse.gbif.org/t/biotic-relationships-are-reciprocal-relations-needed/3805/13) about reverse entity relationships.

**Comment by MortenHofft** [comment]
NB: this isn't an opinion about what is best and wether we should have both. Just that it is convenient for me right now that it is the same. Thanks @acbentley that would be nice then.
