### ISSUE TITLE
specify: latest version

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#79]
@acbentley could you upload the latest greatest version to the repo in your folder (not as a comment)? Then I will try to import it. I'm fairly certain your last couple of changes have been lost in comments with file uploads. Once done I can import it again.

**Comment by acbentley** [comment]
I just tried uploading files to the agent_relationship folder under Specify but the files still indicate that they were uploaded 3 weeks ago.  What I am doing wrong?  I went to the folder, selected Upload Files, dragged all files for upload and committed my changes.

**Comment by tucotuco** [comment]
It looks like the only file that was changed in your commit was General
Notes.txt. It sounds like you are using a Git UI. I am not familiar with
any of those to know what to suggest.

**Comment by acbentley** [comment]
Yes, that file seems to have uploaded successfully but I used the below method for agent_relationships and nothing seems to have uploaded.  Do I maybe not have privileges for sub-directories?
![Capture](https://user-images.githubusercontent.com/7501989/221643052-90ff8365-c38b-44c3-81c8-dca0069d6b54.JPG)

**Comment by acbentley** [comment]
The screen above is what I get when uploading files.  You can see the four files I am trying to upload to that directory to overwrite the existing files of the same name.  Once I hit Commit changes at the bottom it just takes me back to the master directory.  I do not get any error messages or anything.

**Comment by tucotuco** [comment]
I don't know what is going wrong. In the interests of getting data and not futzing, can you make all the files that need updating in a folder on Google Drive and send me a link via email? I'll try the same method and see if I can learn anything, and failing that, use the good ole command line to get them in there the way I normally do it.

**Comment by tucotuco** [comment]
OK, I think I have all the files updated from the versions on Dropbox.
