### ISSUE TITLE
BGBM: CSV per table

### ISSUE THREAD

**Issue by timrobertson100** [gbif/model-material#82]
To aid loading consistently, can we please get BGBM as a CSV per table (gzipped tar of CSVs)

**Comment by jholetschek** [comment]
Done. I've used the same options... 
COPY .... WITH DELIMITER ',' CSV HEADER;

**Comment by timrobertson100** [comment]
Thanks @jholetschek 
Did you forget to commit perhaps? I don't have the CSVs

**Comment by timrobertson100** [comment]
Thanks @jholetschek - I got your PR and merged.

Can you please remove the `taxon_confidence_percent` column from `taxon_identification` and offer up a new tar file in a PR? We removed that from the schema following the drop in Q&A call we had.

I tested the files and other than that the data load in. Thanks a million for making it so easy for us with that list of copy commands you provided in email.

**Comment by jholetschek** [comment]
Yeah, already did and created another PR: https://github.com/gbif/model-material/pull/84

**Comment by jholetschek** [comment]
Ahhh... I didn't update my repository before the commit. Guess that's why there is a conflict now - sorry.
Should I cancel the PR, revoke the commit and then do it again?

**Comment by timrobertson100** [comment]
I was lazy and committed it directly. Thanks @jholetschek 

Here is an [example record](http://labs.gbif.org:7003/?cat=B%2010%200059081) on a temporary site. That will go on and offline regularly, as it is a work in progress.
