### ISSUE TITLE
Symbiota: Reformat exports into CSV per table

### ISSUE THREAD

**Issue by timrobertson100** [gbif/model-material#85]
The sql file dump of the DB makes it awkward to mix this into a shared DB, where CSV per table exports are easier allowing a simple script to bring it in (e.g. [BGBM example](https://github.com/gbif/model-material/blob/master/gbif/load-bgbm.sql)).

**Comment by timrobertson100** [comment]
Could I please ask you to pick this up from here @themerekat  @arbolitoloco  as I'm not sure what to do?

We're trying to integrate all the data into a single DB, and CSV files make this easier. I've [documented](https://github.com/gbif/model-material/blob/master/symbiota/README_pt3.md) the process I used to export [CSVs](https://github.com/gbif/model-material/tree/master/symbiota/csv) from the DB dumps you provided so I think this is very close

However, I don't really know the difference between `symbiota_neon` and `symbiota_neon_seinet` and they contain duplicate records (e.g. the agent with key `https://biorepo.neonscience.org/portal/api/v2/collection/362132e9-de5e-4e2c-9b67-75d1d13e6c41`). I assume this is fully expected to you.

Could you please merge this into a format that would load into a shared DB? I presume this means deduplicating somehow. You can see how we will load the data [here](https://github.com/gbif/model-material/tree/master/gbif).

Once we can load it, we can show the result in the UI which is a work in progress. An [example record](http://labs.gbif.org:7003/?cat=B%2010%200059081) from the Berlin Botanical Garden will give you an idea of what to expect (That will go on and offline regularly, as it is a work in progress).

Thank you very much.

**Comment by MortenHofft** [comment]
The GrSciColl collection IDs in e.g. https://github.com/gbif/model-material/blob/master/symbiota/symbiota_neon_seinet.sql#L1270 `019e23e2-f97d-4dcd-95ff-46009106b88b`

I do not see those in GrSciColl? https://registry.gbif.org/collection/019e23e2-f97d-4dcd-95ff-46009106b88b

It looks to me like grscicoll could need cleaning up regarding that entry. But it is probably 
https://registry.gbif.org/collection/ecc505c5-cadd-4cb5-b0b6-b83b9eca4848
or
https://registry.gbif.org/collection/03a64ffd-34d0-432c-a152-0d41d41c028f ?

**Comment by themerekat** [comment]
@timrobertson100 , I think this is what you were looking for? https://github.com/gbif/model-material/pull/90 I just joined the two datasets into one.

**Comment by themerekat** [comment]
@MortenHofft , I used the collectionID from the Symbiota portal. I believe you should be able to find it listed in the GRSciColl identifiers list: https://registry.gbif.org/collection/03a64ffd-34d0-432c-a152-0d41d41c028f/identifier

**Comment by timrobertson100** [comment]
I think it might be a little more than that @themerekat 

You provided 2 database exports and we're trying to load a single database. In the exports there are e.g. the same collection record (https://biorepo.neonscience.org/portal/api/v2/collection/362132e9-de5e-4e2c-9b67-75d1d13e6c41). I can load one of the exports, but the second one obviously fails as it has duplicate keys.

Ideally, what we want is a single directory of CSVs that combines the data from both. Does that make sense?

> I used the collectionID from the Symbiota portal

That is fine for `collection_id` (the primary key) but the `grscicoll_id` has to be the UUID for the record in GRSciColl. If it is e.g. this [GRSciColl entry](https://registry.gbif.org/collection/ecc505c5-cadd-4cb5-b0b6-b83b9eca4848) then `grscicoll_id` would be `ecc505c5-cadd-4cb5-b0b6-b83b9eca4848`.

**Comment by themerekat** [comment]
@timrobertson100 , I may still not be understanding. If you ignore/delete occurrences_dbg.csv and occurrences.csv, then you can just use symb_combined_occurrences and there should be no duplicate records.
The obviously means that references to occurrences_dbg and occurrences would need to be changed to symb_combined_occurrences in the SQL queries. Let me know!

**Comment by timrobertson100** [comment]
I think you might be correct, but can you please run your procedure and provide a single set of CSVs that come out? What we want are the output files (ideally as a set of CSVs rather than a DB dump) that we can use. [This](https://github.com/gbif/model-material/blob/master/symbiota/README_pt3.md) will probably provide the commands you need to generate the CSVs.

**Comment by timrobertson100** [comment]
I looked over the SQL and I _think_ this should be relatively easy, but the README and README pt2 are slightly different and I'm not 100% sure what to do. I think what is needed here is:

- merge the readme 1&2 into a single set of instructions
- remove the CSV and database files no longer used
- run the instructions against the combined data
- export the data as CSVs (see readme 3 as an example)
- commit and PR (please include the CSVs)

Can you please look at that @themerekat or @arbolitoloco ? Thank you

**Comment by timrobertson100** [comment]
Thank you very much @themerekat @arbolitoloco 

I haven't explored yet, but the data all loads now using those latest PRs you both provided. 

Examples:

http://labs.gbif.org:7003/?entityId=4f6a6ac4-651b-4e8e-a1ee-45c459d29b99
http://labs.gbif.org:7003/?entityId=cd3fdc48-8047-4edd-bb04-e2c5ba229796
