### ISSUE TITLE
BGBM: Collection ID constraint 

### ISSUE THREAD

**Issue by timrobertson100** [gbif/model-material#87]
I'm sorry @jholetschek  but a missing FK was spotted and added #86 

This has now broken the BGBM import:

```
psql:load-bgbm.sql:25: ERROR:  insert or update on table "material_entity" violates foreign key constraint "material_entity_collection_id_fkey"
DETAIL:  Key (collection_id)=(fceacd29-9f6c-4c9c-a4bc-67795f9cb972) is not present in table "collection".
```

Would you please use the UUID in the PK for collection instead of `1`? It can stay in the GRSciColl column as well.

Your table looks like this:

```
collection_id,collection_type,collection_code,institution_code,grscicoll_id
1,HERBARIUM,Herbarium Berolinense,B,fceacd29-9f6c-4c9c-a4bc-67795f9cb972
```
Remember collection extends agent, so the ID in agent.csv also needs changed from ´1´

**Comment by jholetschek** [comment]
Strange I didn't get this violation when I reloaded the dump myself!
I've updated tables collection and agent (they share the same PK) and put them into the repository separately. If everything's fine, I will also replace the tar file.

**Comment by jholetschek** [comment]
Why is that always causing a conflict?

**Comment by timrobertson100** [comment]
> Strange I didn't get this violation when I reloaded the dump myself!

I only just added that constraint minutes before opening this issue. It was omitted in error.

Can you give me commit access to your repository and I'll get it in sync. It has diverged I think.

**Comment by timrobertson100** [comment]
Thanks for fixing @jholetschek
