### ISSUE TITLE
Specify: event and occurrences

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#91]
https://github.com/gbif/model-material/blob/master/data-mapping.md#12-occurrences-and-other-events

> Every Occurrence must have a corresponding Event record in which the eventID is the same is the occurrenceID and the eventType for the Event record MUST be OCCURRENCE.

But if I take e.g. the first occurrenceId `bb2deddf-98cb-a120-1451-66e1e4a20878` and go to the event table

I get this record from the EVENT.csv: `bb2deddf-98cb-a120-1451-66e1e4a20878,b3cf407a-29af-44f2-af3c-f9a9d3fbe6c3,https://www.gbif.org/dataset/8f79c802-a58c-447f-99aa-1d6a0790825a,a17a1150-49ac-4d8c-9466-fa61aa3cffe4,,COLLECTING_EVENT,,,,,,,,,,,,,,,,,,,,,,
`

Notice `eventType: COLLECTING_EVENT`

I suspect that this is the case where, by oversight, we have missed the possibility to have collection Events attached to material? So for now it would have to be of type `OCCURRENCE`?

**Comment by MortenHofft** [comment]
And all the entries on the event table that currently says `type: OCCURRENCE` are not linked to anything. E.g. id `event_id: 7f034432-c814-4d6d-9ed7-64ff5dff6338` is not mentioned anywhere else than in that table.

**Comment by MortenHofft** [comment]
Related discussion in https://github.com/gbif/model-material/issues/64

**Comment by acbentley** [comment]
I don't understand this and so do not know how to resolve it.

**Comment by timrobertson100** [comment]
I'll try and elaborate on the example above.

Looking at the EVENT.csv you have for example (columns omitted for brevity):

| event_id                             | parent_event_id                      | event_type       |
|--------------------------------------|--------------------------------------|------------------|
| 7f034432-c814-4d6d-9ed7-64ff5dff6338 |                                      | OCCURRENCE       |
| b2f4d840-9961-8164-7de6-10efc12553ff | 7f034432-c814-4d6d-9ed7-64ff5dff6338 | COLLECTING_EVENT |

In the OCCURRENCE.csv you have for example:

| occurrence_id                        | organism_id                          | occurrence_status |
|--------------------------------------|--------------------------------------|-------------------|
| b2f4d840-9961-8164-7de6-10efc12553ff | db1e74a3-1ed3-11e3-bfac-90b11c41863e | PRESENT           |

The `occurrence_id` here of `b2f4d840-9961-8164-7de6-10efc12553ff` has an associated event with an `eventType` of `COLLECTING_EVENT` - that is the issue, as it must be an event of type OCCURRENCE.

I _think_ you intend to describe that there was a single COLLECTING_EVENT (the lot) that included several organisms and we're making an occurrence for each of those.

If so, I think you simply got the OCCURRENCE and COLLECTING_EVENT the wrong way around. The first record in EVENT above is the COLLECTING_EVENT, not the OCCURRENCE, and it is the parent of the OCCURRENCE event.

**Comment by acbentley** [comment]
So, simply switching the event_type for all of these will resolve the issue?

**Comment by timrobertson100** [comment]
I _believe_ so. Swapping the OCCURRENCE and COLLECTING_EVENT around

**Comment by acbentley** [comment]
OK, done and uploaded new file

**Comment by timrobertson100** [comment]
Thanks @acbentley - I've verified the files and that issue looks corrected - they load into my local DB.
I'll coordinate with @MortenHofft tomorrow to test them in the user interface.
