### ISSUE TITLE
Conabio-bees: data import

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#95]
Hi @jmbarrios
It would be really useful if you could normalize your data slightly more. It looks like it might be as simple as concatenating a few files and rename them so that they match the names used in the model (e.g. location vs locality). That would save us from guessing when importing the data.

See https://github.com/gbif/model-material/issues/94 for a more elaborate description

Thank you!

**Comment by jmbarrios** [comment]
Working on that

**Comment by timrobertson100** [comment]
@jmbarrios - I'm afraid I can't load the data.

1. In `entity_relationship` the [first column is an ID](https://github.com/gbif/model-material/blob/master/schema.sql#L486) for the relationship statement (i.e. a primary key) so needs to be unique. 

2. The `entity_relationship_order` is also required - can you please fill that column? (use 0 if there is only one statement per pair of objects)

3. The `dataset_id` is a [required field](https://github.com/gbif/model-material/blob/master/schema.sql#L251) on `materal_entity` - can you please fill that column? (It can be anything, so `connabio_bees` would be fine for example)

4. `dataset_id` is required on `event` (as above)

5. `geodetic_datum` is a [required field](https://github.com/gbif/model-material/blob/master/schema.sql#L112) on georeference. Can you please fill it?

6. `material_entity` has many rows starting from line 17275 that only have IDs so violate NULL constraints. I suspect they should be deleted, but if not they need to be completed.

7. In `occurrence` the `occurrence_status` [must be](https://github.com/gbif/model-material/blob/master/schema.sql#L453) `PRESENT` or `ABSENT`. Please can you fill it?

8. The `occurrence_evidence` [primary key](https://github.com/gbif/model-material/blob/master/schema.sql#L477) means that an entity can only be listed as one piece of evidence for an occurrence, while here many rows repeat. Please can you distinct them?

I think with those changes, the data will load in and can be reviewed. Thank you very much!

**Comment by jmbarrios** [comment]
@timrobertson100 about 6. This dataset corresponds to a bee collection with information about the plant, where the bee was visiting, on the specimen tag. The corresponding plant specimen was not collected, therefore there's no collection information. 
There are two possibilities to avoid null values:
1.  list this information as entities to keep the entities' relation, or
2.  list the plant information as media entities.
Could you give me some advice on this?

**Comment by tucotuco** [comment]
@jmbarrios Sorry that these questions are just quick, without looking into the data. 
Do those MaterialEntity records with only Ids correspond to plants that were never collected? 
And were the plants photographed? 

If this is the correct scenario, then you can create Organism records (and their parent MaterialEntity and Entity records) for the plants and use those Organisms in the EntityRelationships both for the relationships to the bees and for the relationships to the images (DigitalEntities with their parent Entities). Does that make sense?

**Comment by jmbarrios** [comment]
Plants weren't collected neither photographed. 
Plant organism will be created to associate with the entities.
Thanks @tucotuco for your feedback.

**Comment by timrobertson100** [comment]
Hi @jmbarrios 

A couple more things are needed to get this to load I'm afraid:

1. `taxon_formula` is required on the `identification` table. Yours are all `A`.
2. `identification_type` is required on the `identification` table. Yours are all `A`.
3. There are duplicate primary keys in identification (e.g. `9020fac03d9e732131eecd1002ed820b956c3d73`)

**Comment by tucotuco** [comment]
Hi @jmbarrios ,

For the identification_type we recommend values from this controlled vocabulary:

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctnature_of_id

**Comment by timrobertson100** [comment]
@jmbarrios - can you please make one final change on the identification.csv?
It has an `index` in the second column that shouldn't be there.
I removed it manually, and it loads, but it would be good to get that into your script.

With that change, we can load the data and I can close this issue, and we can look at the content of the data.
Thank you very much

**Comment by jmbarrios** [comment]
Done

**Comment by timrobertson100** [comment]
Thank you @jmbarrios 

The data now all loads and any entityID can be added to view a record, [example](http://labs.gbif.org:7003/?entityId=c4c44c9970ff46014801f0ef53b1c62043b996f7)

@tucotuco - we can now review this data and offer any comments.
